name: ci-build-and-tag

on:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup semantic-release
      run: |
        npm install -g semantic-release \
        @semantic-release/changelog \
        @semantic-release/commit-analyzer \
        @semantic-release/exec \
        semantic-release/git \
        semantic-release/release-notes-generator

    - name: Tag a new release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: chmod +x ./prepare-release.sh && npx semantic-release
