name: Build and Test

on:
  push:
    branches-ignore:
      - 'main'
      - 'release*'

jobs:
  test:
    name: Build, test and coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Maven Package
        run: mvn -B clean package -DskipTests

      - name: Maven Verify
        run: mvn -B clean verify

      - name: Coverage test
        uses: codecov/codecov-action@v2
