name: Build and Publish

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: Build, test and Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Coverage test
      uses: codecov/codecov-action@v2

    - uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: sanderdona/charger-service
        registry: docker.io
        addLatest: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
